// packages/create-jitar/templates/react/src/App.tsx
import './App.css'
import reactLogo from './assets/react.svg'
import jitarLogo from './assets/jitar.svg'
import { sayHello } from './shared/sayHello'

const message = await sayHello('Vite + React + Jitar')

function App()
{
  return (
    <div className="App">
      <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <a href="https://jitar.dev" target="_blank">
          <img src={jitarLogo} className="logo jitar" alt="Jitar logo" />
        </a>
      <h1>{message}</h1>
    </div>
  )
}

export default App

// packages/create-jitar/templates/5-solid/src/App.tsx

import solidjslogo from './logo.svg';
import jitarLogo from './assets/jitar.svg';
import type { Component } from 'solid-js';
import { createResource } from 'solid-js';
import { sayHello } from './shared/sayHello';

const sayHelloResource = async () => {
  return await sayHello('Vite + Solid + Jitar');
}

const App: Component = () => {
  const [message] = createResource(sayHelloResource);

  return (
    <>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://solidjs.com" target="_blank">
          <img src={solidjslogo} class="logo solid" alt="Solid logo" />
        </a>
        <a href="https://jitar.dev" target="_blank">
          <img src={jitarLogo} class="logo jitar" alt="Jitar logo" />
        </a>
        <h1>{ message }</h1>
    </>
  );
};

export default App;
